feat: add package command to serverless compose library
serverless/compose pull request #150
Opened 2022-07-22 11:21 UTC by chris-hinds

This PR adds the ability to run `serverless package` in the context of `serverless compose`.

The context for why this is a useful addition: https://serverless-contrib.slack.com/archives/CA4QT5VU3/p1658415216244289

A new test has been added to ensure the correct execution of the `package` command.

2022-07-25 12:20 UTC, pgrzesik requested changes
Thanks @chris-hinds - I have a question, please let me know what do you think.

Additionally, we didn't consider `package` for a global command because we've had some future plans, where having `package` command as a global one might not make sense. What is your opinion on it right now @mnapoli? Do you think it would make sense to have `package` global command?

2022-07-25 12:20 UTC, pgrzesik commented on components/framework/index.js
> +    // Skip retrieving outputs via `sls info` if we already have outputs (faster)
what is the reason for this logic? I don't think it should be even considered for `package`, because outputs might even not exist if the service wasn't deployed beforehand

2022-07-25 12:23 UTC, chris-hinds commented on components/framework/index.js
> +    // Skip retrieving outputs via `sls info` if we already have outputs (faster)
> 

This was just a copy and paste from the similar `deploy()` function. If it is not required this can be removed. I just wasn't sure about it myself.

2022-07-26 12:26 UTC, chris-hinds commented on components/framework/index.js
> +    // Skip retrieving outputs via `sls info` if we already have outputs (faster)
@pgrzesik any more news on this?

2022-07-26 12:28 UTC, mnapoli commented
We discussed it offline and think this could be a good improvement. @pgrzesik will follow up later with concrete suggestions on the code.

2022-07-26 15:03 UTC, pgrzesik commented on components/framework/index.js
> +    // Skip retrieving outputs via `sls info` if we already have outputs (faster)
In my opinion it doesn't make sense to do so because it fetches outputs from deployed service, in case of `package` it's very likely that there is not deployed service and package should not change any CF outputs anyway

2022-07-26 15:04 UTC, pgrzesik commented on src/ComponentsService.js
> +    await this.executeComponentsGraph({ method: 'package', reverse: false });
Any particular reason why you feel it should be executed in graph? It makes sense for commands that can result in new outputs or require dependency on other services. In case of package I think it would be better to invoke all of them in parallel. What do you think?

2022-07-28 08:49 UTC, chris-hinds commented on src/ComponentsService.js
> +    await this.executeComponentsGraph({ method: 'package', reverse: false });
How would this affect params being passed to different services via compose? Or is this not related at all?

2022-07-28 08:50 UTC, mnapoli commented on src/ComponentsService.js
> +    await this.executeComponentsGraph({ method: 'package', reverse: false });
That wouldn't be impacted, as all component outputs are stored in the `.serverless/` folder. So running `package` in parallel would resolve params using the stored outputs.

Since packaging services don't change outputs, we don't have to run following the graph order.

2022-07-28 08:51 UTC, chris-hinds commented on components/framework/index.js
> +    // Skip retrieving outputs via `sls info` if we already have outputs (faster)
Updated and removed the outputs logic.

2022-07-28 08:53 UTC, chris-hinds commented on src/ComponentsService.js
> +    await this.executeComponentsGraph({ method: 'package', reverse: false });
Ok, that makes sense. Do you have an example of how this can be invoked in parallel? This work was mostly a copy and paste of the deploy logic :)

2022-07-28 09:19 UTC, mnapoli commented on src/ComponentsService.js
> +    await this.executeComponentsGraph({ method: 'package', reverse: false });
Sure, there's this method:

https://github.com/chris-hinds/serverless-compose/blob/c702b4c42773e3a53468e8e667342b2d343e1390/src/ComponentsService.js#L330-L332

2022-07-28 10:54 UTC, chris-hinds commented on src/ComponentsService.js
> +    await this.executeComponentsGraph({ method: 'package', reverse: false });
Perfect thanks @mnapoli have made the request changes

2022-07-28 11:22 UTC, mnapoli commented on components/framework/index.js
> +    }
I think we can remove these 4 lines here, they won't be useful.

2022-07-28 11:36 UTC, pgrzesik requested changes
Thanks @chris-hinds, looks good in general, I only have a few comments, please let me know what do you think

2022-07-28 11:36 UTC, pgrzesik commented on components/framework/index.js
> +    }
agreed, let's remove these

2022-07-28 11:36 UTC, pgrzesik commented on src/ComponentsService.js
> +    // Resolve the status of components that were not packaged
I don't think it's going to be needed. Did you have a situation where this logic was needed? It would make sense if some components were skipped due to errors in their dependency chain, but since everything is running in parallel it seems like it's simply dead code

2022-07-28 11:46 UTC, mnapoli commented on src/ComponentsService.js
> +    // Resolve the status of components that were not packaged
Ah yes that's a good point, I think all this can be replaced with a simpler approach like:

```js
  async package() {
    this.context.output.log();
    this.context.output.log(`Packaging for stage ${this.context.stage}`);

    await this.invokeComponentsInParallel('package');
  }
```

2022-07-28 11:54 UTC, chris-hinds commented on src/ComponentsService.js
> +    // Resolve the status of components that were not packaged
> I don't think it's going to be needed. Did you have a situation where this logic was needed? It would make sense if some components were skipped due to errors in their dependency chain, but since everything is running in parallel it seems like it's simply dead code

No particular use case, just a copy, and paste from the deploy method

2022-07-28 11:55 UTC, chris-hinds commented on src/ComponentsService.js
> +    // Resolve the status of components that were not packaged
Updated with requested changes, tests still passing 👍

2022-07-28 13:18 UTC, mnapoli commented on components/framework/index.js
> +    await this.exec('serverless', ['package']);
Just noticed that the progress is probably never turned into a success, did you notice that when testing?

It might be necessary to switch to this:

```suggestion
    await this.exec('serverless', ['package']);
    
    this.context.successProgress('packaged');
```

2022-07-28 13:18 UTC, mnapoli commented
I noticed one final problem, sorry. After that I think that's all good for me.

2022-07-28 14:15 UTC, chris-hinds commented on components/framework/index.js
> +    await this.exec('serverless', ['package']);
Good spot! I also noticed I missed the options object which was actually causing a failure. 

<img width="394" alt="image" src="https://user-images.githubusercontent.com/14273378/181531435-1d22d6a9-bf96-4da0-932c-df2cceacccae.png">

2022-07-29 07:31 UTC, mnapoli approved these changes
All good for me, thanks!

Waiting for @pgrzesik if you have anything else, then we can merge.

2022-07-29 08:06 UTC, pgrzesik requested changes
Thanks @chris-hinds - there's a formatting check failing, but after fixing it we should be good to go

2022-07-29 09:20 UTC, chris-hinds commented
> Thanks @chris-hinds - there's a formatting check failing, but after fixing it we should be good to go

Just pushed a fix, hopefully, those checks pass now. Thanks for all your help @pgrzesik and @mnapoli

2022-07-29 13:49 UTC, pgrzesik approved these changes
Thanks @chris-hinds, it looks good 👍

2022-07-29 13:50 UTC, merged

2022-07-29 14:03 UTC, chris-hinds commented
Thanks both. How long until this would be available in compose via NPM?

2022-07-29 14:28 UTC, pgrzesik commented
It should be available @chris-hinds with `v1.3.0` release